/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Color;
import Conectar.Conectar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author victo
 */
public class Vender extends javax.swing.JFrame {

    /**
     * Creates new form eee
     */
    public Vender() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
        productoVender = new ProductoVender();
    }
    ProductoVender productoVender = new ProductoVender();
    private Object[][] obtenerDatosDeTabla(JTable tabla) {
        int rowCount = tabla.getRowCount();
        int columnCount = tabla.getColumnCount();
        Object[][] data = new Object[rowCount][columnCount];

        for (int i = 0; i < rowCount; i++) {
            for (int j = 0; j < columnCount; j++) {
                data[i][j] = tabla.getValueAt(i, j);
            }
        }
        return data;
    }
    public void verificarTabla() {
    if (productoVender.getTablaProd() != null) {
        System.out.println("TablaProd no es null");
        System.out.println("Número de filas en TablaProd: " + productoVender.getTablaProd().getRowCount());
    } else {
        System.out.println("TablaProd es null");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sproducto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mpago = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Vender = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Lista = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Fiar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(741, 512));
        setResizable(false);
        setSize(741,512);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("VENDER");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menup.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(249, 249, 249)
                .addComponent(jLabel6)
                .addGap(0, 294, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 140));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setText("PRODUCTO");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 140, 30));

        sproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compracarro.png"))); // NOI18N
        sproducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sproductoMouseClicked(evt);
            }
        });
        bg.add(sproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 70, 70));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel8.setText("METODO DE PAGO");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        mpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mpago.setBorder(null);
        bg.add(mpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 170, 40));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel9.setText("FECHA");
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        fecha.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        fecha.setForeground(new java.awt.Color(204, 204, 204));
        fecha.setText("Ingrese la fecha...");
        fecha.setBorder(null);
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaMousePressed(evt);
            }
        });
        bg.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 170, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, 10));

        Vender.setBackground(new java.awt.Color(0, 102, 204));
        Vender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VenderMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        jLabel7.setText("VENDER");

        javax.swing.GroupLayout VenderLayout = new javax.swing.GroupLayout(Vender);
        Vender.setLayout(VenderLayout);
        VenderLayout.setHorizontalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VenderLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        VenderLayout.setVerticalGroup(
            VenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        bg.add(Vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 170, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        Lista.setBackground(new java.awt.Color(0, 102, 204));
        Lista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ListaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ListaMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listaventas.png"))); // NOI18N
        jLabel10.setText("LISTA");

        javax.swing.GroupLayout ListaLayout = new javax.swing.GroupLayout(Lista);
        Lista.setLayout(ListaLayout);
        ListaLayout.setHorizontalGroup(
            ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        ListaLayout.setVerticalGroup(
            ListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        bg.add(Lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 170, -1));

        Fiar.setBackground(new java.awt.Color(0, 102, 204));
        Fiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FiarMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fiar.png"))); // NOI18N
        jLabel11.setText("FIAR");

        javax.swing.GroupLayout FiarLayout = new javax.swing.GroupLayout(Fiar);
        Fiar.setLayout(FiarLayout);
        FiarLayout.setHorizontalGroup(
            FiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FiarLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(40, 40, 40))
        );
        FiarLayout.setVerticalGroup(
            FiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        bg.add(Fiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMousePressed
        if (fecha.getText().equals("Ingrese la fecha...")){
            fecha.setText("");
            fecha.setForeground(Color.black);
        }
    }//GEN-LAST:event_fechaMousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Menu me = new Menu ();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseClicked
        Listaventas l = new Listaventas();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ListaMouseClicked

    private void FiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiarMouseClicked
        Fiar fi = new Fiar();
        fi.setVisible(true);
    }//GEN-LAST:event_FiarMouseClicked

    private void VenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseClicked
       JTable tablaProd = productoVender.getTablaProd();
       Object[][] datos = obtenerDatosDeTabla(tablaProd);
       String InsertVenta = "insert into Ventas (fecha_venta, metodo_pago) values (?,?,?)";
       String InsertVenta_prod = "Insert into Venta_prod (id_producto, id_venta, cantidad) values (?,?,?)";
       String ActualizarStock = "update Productos stock = stock - ? where idProducto = ?";
       String IdProductoSelect ="select IdProducto from Productos where Producto = ?";
       Conectar conecta = new Conectar();
       try(Connection con = conecta.getConexion();){
           con.setAutoCommit(false);
           
           PreparedStatement stmt = con.prepareStatement(InsertVenta);
           stmt.setString(1, fecha.getText());
           stmt.setString(2, (String) mpago.getSelectedItem());
           
           ResultSet generatedKeys = stmt.getGeneratedKeys();
            int idVenta = 0;
            if (generatedKeys.next()) {
                idVenta = generatedKeys.getInt(1);
            }
           
           
           TableModel modelo = tablaProd.getModel();
           int rowCount = modelo.getRowCount();
           
           for (int i = 0; i < rowCount; i++) {
                String Producto = (String) modelo.getValueAt(i, 0);
                int cantidad = (Integer) modelo.getValueAt(i, 1);
                PreparedStatement idProdStmt = con.prepareStatement(IdProductoSelect);
                idProdStmt.setString(1, Producto);
                ResultSet rs = idProdStmt.executeQuery();
                
                int idProducto = 0;
                if (rs.next()) {
                    idProducto = rs.getInt("idProductos");
                }
                rs.close();
                idProdStmt.close();
                
                PreparedStatement stmtt = con.prepareStatement(InsertVenta_prod);
                stmtt.setInt(1, idProducto);
                stmtt.setInt(2, idVenta);
                stmtt.setInt(3, cantidad);
                
                PreparedStatement actualizar = con.prepareStatement(ActualizarStock);
                actualizar.setInt(1, cantidad);
           }                                 
       }
       catch(SQLException e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_VenderMouseClicked

    private void sproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sproductoMouseClicked
        
        productoVender.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_sproductoMouseClicked

    private void ListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseEntered
        Lista.setBackground(new Color (0,120,240));
    }//GEN-LAST:event_ListaMouseEntered

    private void ListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseExited
        Lista.setBackground(new Color (0,102,204));
    }//GEN-LAST:event_ListaMouseExited

    private void FiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiarMouseEntered
        Fiar.setBackground(new Color (0,120,240));
    }//GEN-LAST:event_FiarMouseEntered

    private void FiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiarMouseExited
        Fiar.setBackground(new Color (0,102,204));
    }//GEN-LAST:event_FiarMouseExited

    private void VenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseEntered
        Vender.setBackground(new Color (0,120,240));
    }//GEN-LAST:event_VenderMouseEntered

    private void VenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VenderMouseExited
        Vender.setBackground(new Color (0,102,204));
    }//GEN-LAST:event_VenderMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fiar;
    private javax.swing.JPanel Lista;
    private javax.swing.JPanel Vender;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> mpago;
    private javax.swing.JLabel sproducto;
    // End of variables declaration//GEN-END:variables
}
